//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multinet_customer_portal {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
	}
}
